### ISSUE TITLE
Validate Schema Check

### ISSUE THREAD

**Issue by PhillypHenning** [bitovi/bitops#117]
## Summary
A validation check is needed for bitops.deploy.yaml (incoming config source).

The validation should be performed for the "incoming config source" against the depoy.schema.yaml

If an error / mismatch is found, it should be reported and execution should cease. 

## Example
deploy.schemas.yaml
```
helm:
    cli:
    options:
        kubeconfig:
            fetch:
                enabled: 
                  type: boolean
                  default: false
                  export_env: FETCH_KUBECONFIG
                cluster-name:
                  type: string
                  export_env: CLUSTER_NAME
```

Where as the Helm/bitops.deploy.yaml uses;
```
helm:
  cli:
    namespace: bitops
    debug: false
    atomic: true
    options:
      release-name: bitops-eks 
      kubeconfig:
        fetch:
          enabled: True
          cluster-name: bitops-eks
```

As you can see, in the helm deploy.yaml, 'options' is nested under CLI
