### ISSUE TITLE
bitops-config: Create parameter-list type for bitops-config converter

### ISSUE THREAD

**Issue by mickmcgrath13** [bitovi/bitops#118]
Terraform has a list of parameters all with the same name like:
```
-backend-config="KEY1=VALUE1" \
-backend-config="KEY2=VALUE2"
```

To handle this, we should support the following `bitops.config.yaml`
```
terraform:
    cli:
        backend-config:
        - KEY1=VALUE1
        - KEY2=VALUE2
```

The schema to support this would look like this:
```
terraform:
  type: object
  properties:
    cli:
      type: object
      properties:
        backend-config:
          type: parameter-list
          parameter: backend-config
```

This would currently require a new [converter](https://github.com/bitovi/bitops/tree/master/scripts/bitops-config/converters) which would iterate the `parameter-list` and output each `-${key}="${item}"` (where `$key` is the parameter name and each `$item` is an array item).
