### ISSUE TITLE
bitops-config: support single dash parameters

### ISSUE THREAD

**Issue by mickmcgrath13** [bitovi/bitops#119]
most cli params are like this: `cli-tool --opt1=foo --opt2=bar`

> *Note* the 2 dashes `--`

Some cli tools use single dashes like: `cli-tool -opt1=foo -opt2=bar`

`bitops.schema.yaml` should support the ability to choose which parameter prefix is used per param like:
```
terraform:
  type: object
  properties:
    cli:
      type: object
      properties:
        backend-config:
          type: parameter-list
          parameter: backend-config
          parameter-prefix: "-"
```
