### ISSUE TITLE
Combined parameters files

### ISSUE THREAD

**Issue by PhillypHenning** [bitovi/bitops#131]

**Comment by mickmcgrath13** [comment]
@PhillypHenning can you elaborate a bit?

**Comment by PhillypHenning** [comment]
Jquery to combined json files;
`jq '.[]' parameter-secrets.json versions.json | jq -s . > output.json`

**Comment by mickmcgrath13** [comment]
seems like it'd be pretty straight forward.  I'd "feature flag" it as an opt-in sort of thing.

so we could add something to the schema like:
```
cloudformation:
  type: object
  properties:
    options:
      type: object
      properties:
        merge-parameters:
          type: object
          properties: 

            # opt-in to merging files within the parameters directory
            enabled:
              type: boolean
              default: false
              export_env: CFN_MERGE_PARAMETERS

            # merge everything in this directory into a single file (relative to $CLOUDFORMATION_ROOT)
            directory:
              type: string
              export_env: CFN_MERGE_PARAMETERS_DIR
              default: `parameters`
        
            # define what the final filename is for the merged parameters
            file:
              type: string
              export_env: CFN_MERGE_PARAMETERS_FILE
              default: `parameters.json`
```

so that the bitops config is like this:
```
cloudformation:
  options:
    merge-parameters:
      enabled: true
      directory: parameters
      file: parameters.json
```

and then here: https://github.com/bitovi/bitops/blob/master/scripts/cloudformation/deploy.sh#L52

..we could add something like:
```
if [[ "${CFN_MERGE_PARAMETERS}" == "True" ]] || [[ "${CFN_MERGE_PARAMETERS}" == "true" ]]; then
    jq '.[]'  $CLOUDFORMATION_ROOT/$CFN_MERGE_PARAMETERS_DIR/*.json | jq -s . > "$CFN_MERGE_PARAMETERS_FILE"
fi
```

**Comment by mickmcgrath13** [comment]
after writing that, it seems there's already a section for CF like:
```
cloudformation:
  options:
    cfn-files:
      template-file:
        enabled: true
        template-param-file: "foo"
```
so maybe we could nest it under that?  i'm a bit torn on the additional nesting, though, because it'd be getting rather deep.  I kinda like the other approach ([here](https://github.com/bitovi/bitops/issues/131#issuecomment-961393962)), but i could go either way.

I'm sure you get the idea in any case :)
