### ISSUE TITLE
Add multi-regional deployment support

### ISSUE THREAD

**Issue by PhillypHenning** [bitovi/bitops#138]
# Summary
Multi-regional deployment support is a key feature of AWS. In order to support our current and future client needs, it's been decided that multi-regional deployment support should be added to the capabilities of BitOps. 

The change will need to be made so that it doesn't change the current folder structure only adds to it. 

# Targeted solution
```
cloudformation:
  cli:
    validate-cfn: false
    cfn-stack-action: deploy
  options:
    us-east-1:
      cfn-stack-name: test-stack
      cfn-s3-bucket: test-bucket
      cfn-s3-prefix: test-folder
      capabilities: CAPABILITY_NAMED_IAM
      cfn-files:
        template-file: main-template.yaml
        parameters:
          enabled: true
          template-param-file: parameters.json
          
    us-west-2:
      cfn-stack-name: test-stack
      cfn-s3-bucket: test-bucket
      cfn-s3-prefix: test-folder
      capabilities: CAPABILITY_NAMED_IAM
      cfn-files:
        template-file: main-template.yaml
        parameters:
          enabled: true
          template-param-file: parameters.json
          ```
