### ISSUE TITLE
Consolidate schema

### ISSUE THREAD

**Issue by PhillypHenning** [bitovi/bitops#148]
Currently there are two schemas used by BitOps - Plugins;
- build.config.yaml
- plugins.config.yaml

I believe consolidating the configuration would be beneficial in making the project more understandable. 

Example config.yaml;

```
bitops:
  environment: testing
  
  logging: 
    level: verbose
    file: bitops.logs
    err: bitops.logs
    rotation: 3
  
  plugins:
    aws:
      region: us-east-2
      source: https://github.com/bitops-plugins/bitops-aws-plugin

    terraform:
      source: https://github.com/bitops-plugins/bitops-terraform-plugin
      version: 0.13.0
      logging: 
        level: verbose

    helm:
      version: 3.4.1
      namespace: default
      source: https://github.com/bitops-plugins/bitops-helm-plugin
      logging: 
        level: verbose
        file: bitops.helm.logs
        err: bitops.helm.err
    
    kubectl:
      version: 1.13.7
      source: https://github.com/bitops-plugins/bitops-kubectl-plugin

    ansible:
      version: 2.5
      source: https://github.com/bitops-plugins/bitops-ansible-plugin

    cloudformation:
      source: https://github.com/bitops-plugins/bitops-cloudformation-plugin
```
