### ISSUE TITLE
Updating build.config.yaml  plugins "version"

### ISSUE THREAD

**Issue by PhillypHenning** [bitovi/bitops#153]
Change plugin.*.version to source_tag
Add source_branch

Add logic to pull, if both are present, use branch, if neither are present, pull base

**Comment by PhillypHenning** [comment]
https://github.com/bitovi/bitops/tree/3c71862f7de2df65ce44775dd3d829fe348b7ce0

**Comment by PhillypHenning** [comment]
```

#9 [5/1] RUN python3 scripts/plugins.py install
#9 sha256:e382e6d2e89867a1492963d906b89a73bdb149ac25202288d4cb6a81227542c1
#9 0.447 Loading build.config.yaml
#9 0.447 Preparing plugin: [aws]
#9 0.447 Plugin source cannot be empty. Plugin: [aws]
#9 0.447 Download did not run
#9 0.447 Preparing plugin: [terraform-usage1]
#9 0.447 Downloading plugin: [terraform-usage1], from: [https://github.com/bitops-plugins/bitops-terraform-plugin], , using tag: [v0.0.1]
#9 0.447 Download completed
#9 0.447 Preparing plugin: [terraform-usage2]
#9 0.447 Downloading plugin: [terraform-usage2], from: [https://github.com/bitops-plugins/bitops-terraform-plugin], , using branch: [test]
#9 0.447 Download completed
#9 0.447 Preparing plugin: [helm]
#9 0.447 Downloading plugin: [helm], from: [https://github.com/bitops-plugins/bitops-helm-plugin], , using branch: [test]
#9 0.447 Download completed
#9 0.447 Preparing plugin: [kubectl]
#9 0.447 Downloading plugin: [kubectl], from: [https://github.com/bitops-plugins/bitops-kubectl-plugin], using branch: [master] 
#9 0.447 Download completed
#9 0.447 Preparing plugin: [ansible]
#9 0.447 Downloading plugin: [ansible], from: [https://github.com/bitops-plugins/bitops-ansible-plugin], using branch: [master] 
#9 0.447 Download completed
#9 0.447 Preparing plugin: [cloudformation]
#9 0.447 Downloading plugin: [cloudformation], from: [https://github.com/bitops-plugins/bitops-cloudformation-plugin], using branch: [master] 
#9 0.447 Download completed
#9 DONE 0.5s
```

**Comment by PhillypHenning** [comment]
Working on updating the Git Pull command now

**Comment by PhillypHenning** [comment]
```
#9 [5/1] RUN python3 scripts/plugins.py install
#9 sha256:99835868f2a60b542bdb23827061c7dc88f1337926b0e91fc7305126fd5b77cb
#9 7.029 Loading build.config.yaml
#9 7.029 Preparing plugin: [aws]
#9 7.029 Plugin source cannot be empty. Plugin: [aws] Download did not run
#9 7.029 Preparing plugin: [terraform-usage1]
#9 7.029 Downloading plugin: [terraform-usage1], from: [https://github.com/bitops-plugins/bitops-terraform-plugin], using branch: [v0.0.1]
#9 7.029 Plugin [terraform-usage1] Failed to download
#9 7.029 Preparing plugin: [terraform-usage2]
#9 7.029 Downloading plugin: [terraform-usage2], from: [https://github.com/bitops-plugins/bitops-terraform-plugin], using branch: [test]
#9 7.029 Plugin [terraform-usage2] Failed to download
#9 7.029 Preparing plugin: [helm]
#9 7.029 Downloading plugin: [helm], from: [https://github.com/bitops-plugins/bitops-helm-plugin], using branch: [test]
#9 7.029 Plugin [helm] Failed to download
#9 7.029 Preparing plugin: [kubectl]
#9 7.029 Downloading plugin: [kubectl], from: [https://github.com/bitops-plugins/bitops-kubectl-plugin], using branch: [master]
#9 7.029 Plugin [kubectl] Download completed
#9 7.029 Installing plugin: [kubectl]
#9 7.029 
#9 7.029 When including a plugin in a BitOps install, this script will be called during docker build.
#9 7.029 It should be used to install any dependencies required to actually run your plugin.
#9 7.029 BitOps uses alpine linux as its base, so you'll want to use apk commands (Alpine Package Keeper)
#9 7.029 
#9 7.029 musl
#9 7.029 busybox
#9 7.029 alpine-baselayout
#9 7.029 alpine-keys
#9 7.029 libcrypto1.1
#9 7.029 libssl1.1
#9 7.029 ca-certificates-bundle
#9 7.029 libtls-standalone
#9 7.029 ssl_client
#9 7.029 zlib
#9 7.029 apk-tools
#9 7.029 scanelf
#9 7.029 musl-utils
#9 7.029 libc-utils
#9 7.029 ca-certificates
#9 7.029 libffi
#9 7.029 libintl
#9 7.029 ncurses-terminfo-base
#9 7.029 ncurses-libs
#9 7.029 libbz2
#9 7.029 sqlite-libs
#9 7.029 xz-libs
#9 7.029 expat
#9 7.029 gdbm
#9 7.029 libtirpc-conf
#9 7.029 krb5-conf
#9 7.029 libcom_err
#9 7.029 keyutils-libs
#9 7.029 libverto
#9 7.029 krb5-libs
#9 7.029 libtirpc
#9 7.029 libnsl
#9 7.029 libuuid
#9 7.029 readline
#9 7.029 .python-rundeps
#9 7.029 bash
#9 7.029 nghttp2-libs
#9 7.029 libcurl
#9 7.029 curl
#9 7.029 pcre2
#9 7.029 git
#9 7.029 oniguruma
#9 7.029 jq
#9 7.029 libsodium
#9 7.029 pkgconf
#9 7.029 libsodium-dev
#9 7.029 unzip
#9 7.029 libunistring
#9 7.029 libidn2
#9 7.029 wget
#9 7.029 
#9 7.029 Preparing plugin: [ansible]
#9 7.029 Downloading plugin: [ansible], from: [https://github.com/bitops-plugins/bitops-ansible-plugin], using branch: [master]
#9 7.029 Plugin [ansible] Download completed
#9 7.029 Installing plugin: [ansible]
#9 7.029 
#9 7.029 When including a plugin in a BitOps install, this script will be called during docker build.
#9 7.029 It should be used to install any dependencies required to actually run your plugin.
#9 7.029 BitOps uses alpine linux as its base, so you'll want to use apk commands (Alpine Package Keeper)
#9 7.029 
#9 7.029 https://releases.hashicorp.com/terraform//terraform__linux_amd64.zip
#9 7.029 Archive:  terraform__linux_amd64.zip
#9 7.029 
#9 7.029 Preparing plugin: [cloudformation]
#9 7.029 Downloading plugin: [cloudformation], from: [https://github.com/bitops-plugins/bitops-cloudformation-plugin], using branch: [master]
#9 7.029 Plugin [cloudformation] Download completed
#9 7.029 Installing plugin: [cloudformation]
#9 7.029 
#9 7.029 When including a plugin in a BitOps install, this script will be called during docker build.
#9 7.029 It should be used to install any dependencies required to actually run your plugin.
#9 7.029 BitOps uses alpine linux as its base, so you'll want to use apk commands (Alpine Package Keeper)
#9 7.029 
#9 7.029 AWSCLI Already installed.
#9 7.029 
#9 DONE 7.2s
```

**Comment by PhillypHenning** [comment]
*build-config.yaml*
```
plugins:
    plugins_seq:
      - terraform-usage1
      - helm  
      - terraform-usage2

    tools:
      aws:
        region: us-east-2
        

      terraform-usage1:
        source: https://github.com/bitops-plugins/bitops-terraform-plugin
        source_tag: v0.0.1
        version: 0.13.0
        logging: 
          level: verbose
        
      
      terraform-usage2:
        source: https://github.com/bitops-plugins/bitops-terraform-plugin
        source_branch: test
        version: 0.13.0
        logging: 
          level: verbose

      helm:
        version: 3.4.1
        namespace: default
        source: https://github.com/bitops-plugins/bitops-helm-plugin
        source_branch: test
        source_tag: v0.0.1
        logging: 
          level: verbose
          file: bitops.helm.logs
          err: bitops.helm.err
      
      kubectl:
        version: 1.13.7
        source: https://github.com/bitops-plugins/bitops-kubectl-plugin

      ansible:
        version: 2.5
        source: https://github.com/bitops-plugins/bitops-ansible-plugin

      cloudformation:
        source: https://github.com/bitops-plugins/bitops-cloudformation-plugin
```
