### ISSUE TITLE
Add version arg to Plugin install scripts

### ISSUE THREAD

**Issue by PhillypHenning** [bitovi/bitops#154]
# BitOps 
Functionality needs to be added so that a version value can be specified for a plugin within the build.config.yaml, and it should be so that the version is passed to the plugin when the `install.sh` script is invoked.

# Plugin
Bitovi's standard plugins should have the capability to support installation of a specific version when the `install.sh` file is called.

**Comment by PhillypHenning** [comment]
### Bitops support added
*build.config.yaml*
```
...
plugins:
    plugins_seq:
      - terraform-usage1
      
    tools:
      terraform-usage1:
        source: https://github.com/bitops-plugins/bitops-terraform-plugin
        source_tag: v0.0.1
        version: 0.13.0
```


https://github.com/bitovi/bitops/blob/257c85e1fba8b39c94a40bf049e12a60aa2c8218/scripts/plugins/install_plugins.py#L67
