### ISSUE TITLE
Adding `deploy` and `install` language detection + smart invoke

### ISSUE THREAD

**Issue by PhillypHenning** [bitovi/bitops#155]
If install|deploy_script is specified use it, otherwise default to `.sh`

* Example build.config.yaml*
```
terraform-usage1:
        source: https://github.com/bitops-plugins/bitops-terraform-plugin
        source_tag: v0.0.1
        version: 0.13.0
        logging: 
          level: verbose
        install_script: install.py
        deploy_script: deploy.py
        
      
      terraform-usage2:
        source: https://github.com/bitops-plugins/bitops-terraform-plugin
        source_branch: test
        version: 0.13.0
        logging: 
          level: verbose
```
