### ISSUE TITLE
Cloudprovider needs to be explict in config and "identity" script needs to be added to cloudprovider plugins

### ISSUE THREAD

**Issue by PhillypHenning** [bitovi/bitops#156]
The Cloudprovider config value needs to be added into the build.config.yaml, the install+deploy scripts will need to loop through the tools + cloud providers

## build.config.yaml
```
bitops:
  plugins:
    plugins_seq:
      - terraform-usage1
      
    tools:
      cloudproviders:
        aws:
          region: us-east-2

      deployment:
        terraform-usage1:
          source: https://github.com/bitops-plugins/bitops-terraform-plugin
          source_tag: v0.0.1
          version: 0.13.0
          logging: 
            level: verbose
```

I'm thinking something like this would work well to keep things separated and understandable. 

## Plugins
Cloudprovider plugins would be required to have an additional script included, which would be used for identity management

**Comment by mickmcgrath13** [comment]
I like the structure:
```
bitops:
  plugins:
    plugins_seq:
      - terraform-usage1
      
    tools:
      cloudproviders:
        aws:
          source: ...

      deployment:
        terraform-usage1:
          source: ...
```

One note is that `region` should probably be a deploy time configuration via `bitops.config.yaml` or in the pipeline config (i.e. env vars) (or both).

is there anything that the region is needed for at build time?
