### ISSUE TITLE
Github source for BitOps

### ISSUE THREAD

**Issue by PhillypHenning** [bitovi/bitops#169]
**Is your feature request related to a problem? Please describe.**
BitOps needs to be updated to support the sourced_from value in the schema. If an SCM url is specified, install bitops to the `/opt/bitops_deployment/`. If mount is specified, mount the `src` to the `dest` schema values. 

#### URL
```
bitops:
  ops_repo:
    source:
      source_from: https://github.com/bitovi/bitops
```
Attempts to clone the url to the default deployment folder; `/opt/bitops_deployments`

#### URL + Dest
```
bitops:
  ops_repo:
    source:
      source_from:https://github.com/bitovi/bitops
      dest: /opt/bitops_other_deployments

```
Attempts to clone the url to the specified deployment folder; `/opt/bitops_other_deployments`

#### Mount + src
```
bitops:
  ops_repo:
    source:
      source_from: mount
      src: /path/to/local/bitops_folder

```
Attempts to clone the bitops folder at the src path to the default bitops working directory; `/opt/bitops_deployments`

# Additional task
   - Github credentials need to be retrieved and inject safely
