### ISSUE TITLE
remove plugins and deployment blocks from bitops.config.yaml

### ISSUE THREAD

**Issue by PhillypHenning** [bitovi/bitops#252]
**Describe the bug**
Remove the following from the root level `bitops.config.yaml`

```
plugins:    
    aws:
      source: https://github.com/bitops-plugins/aws
    terraform:
      source: https://github.com/bitops-plugins/terraform
    cloudformation:
      source: https://github.com/bitops-plugins/cloudformation
    helm:
      source: https://github.com/bitops-plugins/helm
    kubectl:
      source: https://github.com/bitops-plugins/kubectl
    ansible:
      source: https://github.com/bitops-plugins/ansible
  deployments:
    cloudformation:
      plugin: cloudformation
    terraform:
      plugin: terraform
    helm:
      plugin: helm
    ansible:
      plugin: ansible
```

replace with 
```
plugins: {}
deployments: {}
```
