### ISSUE TITLE
Allow ops repos to override `deployments` order from the BitOps image

### ISSUE THREAD

**Issue by mickmcgrath13** [bitovi/bitops#259]
**Is your feature request related to a problem? Please describe.**
The BitOps image is currently responsible for both installing [plugins](https://github.com/bitovi/bitops/blob/main/bitops.config.yaml#L17) (BitOps repo -> `bitops.config.yaml` -> `bitops.plugins`) and defining [deployment order](https://github.com/bitovi/bitops/blob/main/bitops.config.yaml#L30) (BitOps repo -> `bitops.config.yaml` -> `bitops.deployments` of the plugins.
```
bitops:
  ...
  plugins:    
    aws:
      source: https://github.com/bitops-plugins/aws
    terraform:
      source: https://github.com/bitops-plugins/terraform
    cloudformation:
      source: https://github.com/bitops-plugins/cloudformation
    helm:
      source: https://github.com/bitops-plugins/helm
    kubectl:
      source: https://github.com/bitops-plugins/kubectl
    ansible:
      source: https://github.com/bitops-plugins/ansible
  deployments:
    cloudformation:
      plugin: cloudformation
    terraform:
      plugin: terraform
    helm:
      plugin: helm
    ansible:
      plugin: ansible
```

**Describe the solution you'd like**
The deployment order should be able to be specified via the ops repo environment-level `bitops.config.yaml` (e.g. ops repo -> `envA/bitops.config.yaml`) so that users of BitOps images can rearrange deployment order per environment without having to build a custom BitOps image.

Both BitOps-level `bitops.config.yaml` and operations repo env-level `bitops.config.yaml` should _both_ be able to specify deployment order.  If both are specified, ops repo wins. If ops repo is not specified, it would fall back to the bitops-level deployment config.

Modifications would happen here somewhere: 
- https://github.com/bitovi/bitops/blob/main/scripts/plugins/deploy_plugins.py#L23
