### ISSUE TITLE
Local Plugin Development and Testing

### ISSUE THREAD

**Issue by armab** [bitovi/bitops#308]
Based on https://github.com/bitops-plugins/terraform/pull/7 and https://github.com/bitovi/bitops/issues/307
At this moment the workflow to develop and test the plugins is time-consuming.

For someone to develop and test the plugin locally they need to push the changes to the git repository first, create a `bitops.config.yaml` referencing to the git repository and build a docker image based on https://bitovi.github.io/bitops/plugins/#creating-your-own-bitops-image instructions:

```yaml
bitops:
  plugins:
    terraform:
      source: https://github.com/bitops-plugins/terraform
```

Instead of that, we could implement `file://` handler that would allow using the local plugin directory:
```yaml
bitops:
  plugins:
    terraform:
      source: file:///path-to-local-bitops-plugin/
```

This will help with the local development, as well as open opportunity for the automated testing [Plugins: Testing / Validation and CI/CD #224](https://github.com/bitovi/bitops/issues/224) for every plugin, so we can verify that the plugin install really works and verified against the base BitOps on every PR as we change them.
