### ISSUE TITLE
Helm upgrade docs are incorrect for k8s fetch

### ISSUE THREAD

**Issue by mickmcgrath13** [bitovi/bitops#326]
**Why are you updating / adding this documentation?**
[Helm upgrade docs](https://bitovi.github.io/bitops/migration/2.0-migration/#terraform) say: 
```
helm.option.kubeconfig.fetch.enabled --> Changed to --> helm.option.kubeconfig.fetch.fetch_kubeconfig
```

However, the [schema](https://github.com/bitops-plugins/helm/blob/main/bitops.schema.yaml#L57) says:
```
helm:
  type: object
  properties:
    # other stuff
    options:
      type: object
      properties:
        # other stuff
        k8s:
          type: object
          properties:
            kubeconfigpath:
              type: string
              export_env: KUBE_CONFIG_PATH
            fetch:
              type: object
              properties:
                kubeconfig: 
                  type: boolean
                  default: true
                  export_env: FETCH_KUBECONFIG
                cluster-name:
                  type: string
                  export_env: CLUSTER_NAME
```

The docs should say:
```
helm.options.kubeconfig.fetch.enabled --> Changed to --> helm.options.k8s.fetch.kubeconfig
```
