### ISSUE TITLE
2.0 Migration doc example with wrong definition

### ISSUE THREAD

**Issue by LeoDiazL** [bitovi/bitops#334]
**Why are you updating / adding this documentation?**
[2.0 Migration doc](https://bitovi.github.io/bitops/migration/2.0-migration/) says:

```
Old method

terraform:
  cli: {}
  options:
    command: apply

New method

terraform:
  cli:
    stack-action: apply

```

Should say 

```
Old method

terraform:
  cli: {}
  options:
    command: apply

New method

terraform:
    cli: {}
    options:
        stack-action: apply
```

**Additional context**
