### ISSUE TITLE
CLI args to the plugins are not passed

### ISSUE THREAD

**Issue by armab** [bitovi/bitops#360]
Originally found in https://github.com/bitops-plugins/terraform/issues/20.

BitOps core implements plugin schema parsing so the params having `export_env` result in a new ENV var exported:
https://github.com/bitops-plugins/helm/blob/7c19ffe743e374de63945f1af70fb470a1bafc04/bitops.schema.yaml#L25-L33

This works OK via `export_env`:
```yaml
helm:
  type: object
  properties:
    cli:
      debug:
        type: boolean
        parameter: debug
        export_env: HELM_DEBUG
```

However, populating and passing the raw CLI args based on the plugin schema is not implemented:
```yaml
terraform:
  type: object
  properties:
    cli:
      backend-config:
        type: list
        parameter: backend-config
        dash_type: "-"
```

This means it's not possible to just add the new CLI param in the plugin schema and consider it'll be sent to the plugins's binary even if [`plugin.deployment.core_schema_parsing: true` in the `plugin.config.yaml`](https://github.com/bitops-plugins/terraform/blob/71ebf01ace789d9ddde8f25e04449d7cb67adfb0/plugin.config.yaml#L9).

Some plugins like helm workaround this internally by trying to parse the schema on the plugin side, but the core implementation is missing.

**Comment by PhillypHenning** [comment]
# Testing 
I agree that this functionality is no longer working; 

**bitops.config.yaml**
```
terraform:
  cli:  
    backend-config:
        type: list
        parameter: backend-config
        dash_type: "-"
    stack-action: destroy
  options: {}
  ```


```
2022-11-21 20:40:09,569 root         DEBUG 
        SCHEMA:
                Name:         [backend-config]            
                Schema Key:   [terraform.properties.cli.properties.backend-config]            
                Config_Key:   [terraform.cli.backend-config]            
                Schema Type:  [cli]            
                                  
                Export Env:   [None]            
                Default:      [None]            
                Enabled:      [None]            
                Type:         [list]            
                Parameter:    [backend-config]            
                Dash Type:    [-]            
                Required:     [None]            
                                  
                Value Set:    [['type', 'parameter', 'dash_type']]
```

**Comment by PhillypHenning** [comment]
Actually thinking about this. I'm not sure this is even what we should offer... 

Instead I think it would be better to offer (across all plugins) an `EXTRA_VARS` value that allows individuals to specify flags, k/v pairs, etc and just merge it into the command appropriately. 

Example; 

`terraform apply <EXTRA_VARS applied here>`

**Comment by armab** [comment]
A catch-all `EXTRA_ARGS` ENV var (and respective `extra_args` setting in the bitops.config.yaml) user can set to pass to the plugin might be an option 👍 
I'd normally think about a more structured YAML param approach, but this sounds good and simple enough: 
```
terraform:
  cli:
    stack-action: plan
    extra_args: "-out=<path> -parallelism=<n> -var='foo=bar'"
  options: {}
```

Which will produce:
```
terraform plan -out=<path> -parallelism=<n> -var='foo=bar'
```
