### ISSUE TITLE
User defined plugin order selection

### ISSUE THREAD

**Issue by LeoDiazL** [bitovi/bitops#367]
Nowadays we have a pretty static definition of what to run and when in Bitops.

Even though I know the order can be changed by doing some mods, I think it would be nice to do something that could adapt easily to what the user needs.
I can think of more than one scenario where I would like to run some Ansible playbooks before running Terraform for example, but would like to run an Ansible playbook post terraform excecution too.

I can think of **two approaches.**
- Folder based order. Simple 0  --> Z
- File definition with the order this folders should be read.

We can populate the deployments list by just listing the directories available inside the deployment, and then read which plugin is needed based on the bitops.config.yaml

**Comment by armab** [comment]
From the discussion, the following projects were mentioned where user can control the order of runs in the workflow config:
- https://atmos.tools/core-concepts/workflows/
- https://pypyr.io/
- https://dagger.io/ 

### YAML deployment order control via root-level `bitops.config.yaml`:
```yaml
deployments:
    ansible_first:
      plugin: ansible
    terraform:
      plugin: terraform
    ansible_second:
      plugin: ansible
```

### Alphanumeric dir name order in `bitops.config.yaml` via option:
```yaml
deployment_order: alphanum
```
User names the deployment dirs like `00_ansible`, `01_terraform`, `02_ansible`, or similar.

**Comment by armab** [comment]
Speaking of UX, if going with the YAML config definition, it can consistently work together with a [Feature: Run a Deployment sub-step #318](https://github.com/bitovi/bitops/issues/318).
For instance, having this config:
```
deployments:
  prepare-instance:
    plugin: ansible
  terraform-provision:
    plugin: terraform
  setup-instance:
    plugin: ansible
```

Based on the named deployment definitions, we could potentially provide an option to nicely run the deployment sub-step like this:
```
bitops run prepare-instance
bitops run terraform-provision
bitops run setup-instance
```
