### ISSUE TITLE
BitOps Plugin support for private repos

### ISSUE THREAD

**Issue by ConnorGraham** [bitovi/bitops#60]
Need to implement a pattern in `plugin.config.yml` to support private plugin repos. For example:

```
plugins:
- name: pluginA
  repo: https://github.com/myorg/pluginA.git
  auth:
    # type http or ssh detected by repo prefix
    user:
      type: string
      value: myusername
    user:
      type: string
      value: mytoken
- name: pluginB
  repo: https://github.com/myorg/pluginB.git
  auth:
    user:
      type: env
      value: $GIT_USER #defines which env var to get this value from
    user:
      type: env
      value: $GIT_PASSWORD #defines which env var to get this value from
- name: pluginC
  repo: git@github.com:myorg/pluginC.git
  auth:
    sshkey:
      type: string
      value: |
        -----BEGIN RSA PRIVATE KEY-----
        ...
        -----END RSA PRIVATE KEY-----
- name: pluginD
  repo: git@github.com:myorg/pluginD.git
    sshkey:
      type: env
      value: $GIT_SSHKEY #defines which env var to get this value from
- name: pluginE
  repo: git@github.com:myorg/pluginD.git
    sshkey:
      type: path
      value: /path/to/mounted/sshkey
```

**Comment by mickmcgrath13** [comment]
thanks!

**Comment by mickmcgrath13** [comment]
thanks!

**Comment by armab** [comment]
Going with a simple documentation case first might be a good intermediate state.

If we want to go deeper, from the proposals above, providing `ENV` or `path` for the SSH key to abstract the config creation might be a good option in some future :
```yaml
- name: pluginD
  repo: git@github.com:myorg/pluginD.git
    sshkey:
      type: env
      value: $GIT_SSHKEY #defines which env var to get this value from
- name: pluginE
  repo: git@github.com:myorg/pluginD.git
    sshkey:
      type: path
      value: /path/to/mounted/sshkey
```

We probably don't want entering the entire security story yet where the credentials are supported by the bitops config schema natively, considering the current security state (like #208) and then thinking how to recommend protecting those credentials to the users. So we won't create more problems than we solve.
