### ISSUE TITLE
Enhance logging

### ISSUE THREAD

**Issue by mickmcgrath13** [bitovi/bitops#88]
- Create central functions for logging
- Output colors
- Output JSON

**Comment by mickmcgrath13** [comment]
include debugging

**Comment by PhillypHenning** [comment]
Since we are in the process of enhancing our code, changing the language from Bash to Python, we should utilize the benefits of the logging modules that Python has. 

Logging should be broken up into; 
- Core logs
  - Standard BitOps logs
  - Verbose BitOps logs
- Plugin Logs
  - Standard Plugin logs
  - Verbose Plugin logs     


Logging levels should be set using a config.yaml. 

*build.config.yaml*
```
bitops:
  environment: testing
  logging: 
    level: verbose
    file: bitops.logs
    err: bitops.logs
    rotation: 3
  
  plugins:
    terraform:
      version: 0.13.0
      enabled: True
      logging: 
        level: standard

    helm:
      version: 3.4.1
      namespace: default
      logging: 
        level: verbose
        file: bitops.helm.logs
        err: bitops.helm.err

```


Logging metadata would include; 
_level_ indicates the level of logging that is captured
_file_ indicates where the logs will be stored 
_err_ indicates where the error logs will be stored (Can be the same of different then the _file_ value 
rotation: indicates how long in days before the log files rotate
